### ISSUE TITLE
Relay crash :- While sending messages

### ISSUE THREAD

**Issue by shanithkk** [icon-project/btp2#33]
**Describe the issue**
when i tried e2edemo locally send message from hardhat to icon relay got stopped. im trying to send partial message using loop in the dapp in hardhat side. 
Success scenarios:
1. icon to hardhat normal message
2. icon to hardhat partial messages using loop message
3. hardhat to icon normal message

**To reproduce**
2. create a dapp sending two or more messages using loop
3. Deploy the contracts
4. Run the relay
5. invoke the message
6. ralay will  crash
7. See error

**Expected behavior**
Relay should successfully pass the message to the destination chain

**Screenshots**
![image](https://github.com/icon-project/btp2/assets/59169878/72bab98e-d652-45af-8caf-39343fa14e36)

**System information (please complete the following information):**
 - OS: Mac OS m1 pro

**Comment by kwon528** [comment]
**Questions**
1. Does the relay crash when sending more than one message from a hardhat to icon?

**Request**
1. I checked that there was an error when sending more than two messages from the hardhat to icon. But it was a different crash log from the relay log you delivered.  Can you send it to me in text instead of capturing the relay log?

The bug is being patched. I'll share it with you when it's done.

**Comment by shanithkk** [comment]
Hi @kwon528 , yes. it will happen only when sending multiple message from hardhat to icon

the log you requested is below, i made a log with first successful transaction of normal message and then i made a multiple transaction 

Using BTPBlock mode
I|17:44:37.770190|----|-|main|main.go:273   _____      _             
I|17:44:37.771606|----|-|main|main.go:273  |  __ \    | |            
I|17:44:37.771613|----|-|main|main.go:273  | |__) |___| | __ _ _   _ 
I|17:44:37.771617|----|-|main|main.go:273  |  _  // _ \ |/ _` | | | |
I|17:44:37.771620|----|-|main|main.go:273  | | \ \  __/ | (_| | |_| |
I|17:44:37.771624|----|-|main|main.go:273  |_|  \_\___|_|\__,_|\__, |
I|17:44:37.771628|----|-|main|main.go:273                       __/ |
I|17:44:37.771631|----|-|main|main.go:273                      |___/ 
I|17:44:37.771635|----|-|main|main.go:275 Version : v1.0.0-16-gb8fb77e
I|17:44:37.771683|----|-|main|main.go:276 Build   : darwin/arm64 tags()-2023-05-31-18:34:08
D|17:44:38.139960|b6b5|-|main|main.go:330 LogWriterConfig filename is empty string, will be ignore
D|17:44:38.140933|b6b5|-|main|main.go:367 LogForwarderConfig vendor and address is empty string, will be ignore
D|17:44:38.140940|b6b5|-|main|linkfatory.go:49  
D|17:44:38.140962|f39F|-|main|main.go:330 LogWriterConfig filename is empty string, will be ignore
D|17:44:38.140967|f39F|-|main|main.go:367 LogForwarderConfig vendor and address is empty string, will be ignore
D|17:44:38.140972|f39F|-|main|linkfatory.go:63  .relay/0x3.icon
D|17:44:38.284779|f39F|-|ethbr|receiver.go:225 ReceiveLoop height:31 seq:0 filterQuery[Address:0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9,Topic:0x37be353f216cf7e33639101fd610c542e6a0c0109173fa1c1d8b04d34edb7c1b]
D|17:44:38.310157|f39F|-|ethbr|receiver.go:244 event[seq:1] seq:0 dst:btp://0x3.icon/cx09da9f16b1f8b3d284ed782b2bb9a42992712678
D|17:44:38.310187|f39F|-|ethbr|receiver.go:284 monitor info : Height:40  EventCnt:1 LastSeq:1 
D|17:44:38.310233|f39F|-|ethbr|receiver.go:122 OnBlockOfSrc rpsCnt:1 rxSeq:1
D|17:44:38.310342|f39F|-|ethbr|receiver.go:176 BuildRelayMessage height:40 data:-Gr4aLhm-GQAuGD4XvhcoFCXuP38nItoiRo8At9YJG-qUv97UXHd_BMT6l0DAiuXAbg4940weDUzOS5oYXJkaGF0iDB4My5pY29ug2JtYwCJyIRJbml0gsHAAc-NMHg1MzkuaGFyZGhhdMAo 
D|17:44:38.310374|f39F|-|icon|sender.go:141 _relay src address:btp://0x539.hardhat/0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9, rm id:1314648470020870278, rm msg:f86af868b866f86400b860f85ef85ca05097b8fdfc9c8b68891a3c02df58246faa52ff7b5171ddfc1313ea5d03022b9701b838f78d30783533392e68617264686174883078332e69636f6e83626d630089c884496e697482c1c001cf8d30783533392e68617264686174c028
D|17:44:38.319360|b6b5|-|client|client.go:330 MonitorBTP WSEvent 127.0.0.1:56403 WSEventInit
D|17:44:38.319384|b6b5|-|btp2|btp2.go:311 ReceiveLoop monitorBTP2Block height:61375 seq:1 networkId:10 connected 127.0.0.1:56403
D|17:44:38.351954|b6b5|-|btp2|btp2.go:356 monitor info : Height:61383  UpdateNumber:0  MessageCnt:1  Seq:1 
D|17:44:41.385132|b6b5|-|ethbr|sender.go:190 result success rm id : 4922437019858130275 
D|17:44:41.385423|b6b5|-|btp2|btp2.go:261 clear receive data (height:61383, seq:1) 
D|17:44:42.342966|f39F|-|icon|sender.go:207 result success rm id : 1314648470020870278 
D|17:44:42.343128|f39F|-|ethbr|receiver.go:210 clear receive data (height:40, seq:1) 
D|17:45:14.579766|f39F|-|ethbr|receiver.go:244 event[seq:2] seq:1 dst:btp://0x3.icon/cx09da9f16b1f8b3d284ed782b2bb9a42992712678
D|17:45:14.579825|f39F|-|ethbr|receiver.go:284 monitor info : Height:74  EventCnt:1 LastSeq:2 
D|17:45:14.579867|f39F|-|ethbr|receiver.go:122 OnBlockOfSrc rpsCnt:1 rxSeq:2
D|17:45:14.579914|f39F|-|ethbr|receiver.go:176 BuildRelayMessage height:74 data:-NT40rjQ-M4AuMr4yPjGoFCXuP38nItoiRo8At9YJG-qUv97UXHd_BMT6l0DAiuXArii-KCNMHg1MzkuaGFyZGhhdIgweDMuaWNvboV4Y2FsbAC4b_htAbhq-GiqMHg5NTk5MjJiRTNDQWVlNGI4Q2Q5YTQwN2NjM2FjMUMyNTFDMjAwN0IxqmN4NWE5OWZlNzA2N2RhYjFlZDE1NDRjNzdhM2M3MTNjNzUyNzhhY2Y2ZQEAj84BimhlbGxvX3dvb3IAAALPjTB4NTM5LmhhcmRoYXTASg== 
D|17:45:14.579931|f39F|-|icon|sender.go:141 _relay src address:btp://0x539.hardhat/0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9, rm id:2528975883656175838, rm msg:f8d4f8d2b8d0f8ce00b8caf8c8f8c6a05097b8fdfc9c8b68891a3c02df58246faa52ff7b5171ddfc1313ea5d03022b9702b8a2f8a08d30783533392e68617264686174883078332e69636f6e857863616c6c00b86ff86d01b86af868aa307839353939323262453343416565346238436439613430376363336163314332353143323030374231aa63783561393966653730363764616231656431353434633737613363373133633735323738616366366501008fce018a68656c6c6f5f776f6f72000002cf8d30783533392e68617264686174c04a
D|17:45:18.609347|f39F|-|icon|sender.go:207 result success rm id : 2528975883656175838 
D|17:45:18.609384|f39F|-|ethbr|receiver.go:210 clear receive data (height:74, seq:2) 
D|17:47:06.169122|f39F|-|ethbr|receiver.go:244 event[seq:3] seq:2 dst:btp://0x3.icon/cx09da9f16b1f8b3d284ed782b2bb9a42992712678
D|17:47:06.169581|f39F|-|ethbr|receiver.go:244 event[seq:4] seq:2 dst:btp://0x3.icon/cx09da9f16b1f8b3d284ed782b2bb9a42992712678
D|17:47:06.169594|f39F|-|ethbr|receiver.go:284 monitor info : Height:111  EventCnt:2 LastSeq:4 
D|17:47:06.169653|f39F|-|icon|sender.go:141 _relay src address:btp://0x539.hardhat/0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9, rm id:6363044269861020974, rm msg:
D|17:47:09.205824|f39F|-|icon|sender.go:197 result fail rm id : 6363044269861020974 
P|17:47:09.205887|f39F|0x3|link|link.go:563 fail to GetResult RelayMessage ID:6363044269861020974 ErrorCoder:0
panic: (*logrus.Entry) 0x140001352d0

goroutine 27 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x140001e0070, 0x0, {0x1400002e730, 0x42})
        /Users/shanithkk/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x50c
github.com/sirupsen/logrus.(*Entry).Log(0x140001e0070, 0x0, {0x140000f0ec8?, 0x2?, 0x2?})
        /Users/shanithkk/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Logf(0x140001e0070, 0x0, {0x10479a726?, 0x104688038?}, {0x140001cb120?, 0x104980c00?, 0x14004202d00?})
        /Users/shanithkk/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:349 +0x88
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        /Users/shanithkk/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:387
github.com/icon-project/btp2/common/link.(*Link).result(0x140001e6000, 0x14004294120)
        /Users/shanithkk/Hugobyte/work/macos/icon-project/workspace/btp2test/common/link/link.go:563 +0x28c
github.com/icon-project/btp2/common/link.(*Link).senderChannel.func1()
        /Users/shanithkk/Hugobyte/work/macos/icon-project/workspace/btp2test/common/link/link.go:186 +0x48
created by github.com/icon-project/btp2/common/link.(*Link).senderChannel
        /Users/shanithkk/Hugobyte/work/macos/icon-project/workspace/btp2test/common/link/link.go:182 +0x114

**Comment by kwon528** [comment]
@shanithkk I checked that it is the same log as the error log that I occurred. I will share it as soon as the patch is completed.

**Comment by shanithkk** [comment]
@kwon528 thank you

**Comment by kwon528** [comment]
@shanithkk 
It is successful without any errors when I delivered two messages like the error situation you sent me. 
If you can share the script you used for the test, we will test it with the script that causes an error.

**Relay Log**
Using BTPBlock mode
I|15:35:31.390721|----|-|main|main.go:273   _____      _             
I|15:35:31.390911|----|-|main|main.go:273  |  __ \    | |            
I|15:35:31.390924|----|-|main|main.go:273  | |__) |___| | __ _ _   _ 
I|15:35:31.390933|----|-|main|main.go:273  |  _  // _ \ |/ _` | | | |
I|15:35:31.390941|----|-|main|main.go:273  | | \ \  __/ | (_| | |_| |
I|15:35:31.390950|----|-|main|main.go:273  |_|  \_\___|_|\__,_|\__, |
I|15:35:31.390958|----|-|main|main.go:273                       __/ |
I|15:35:31.390966|----|-|main|main.go:273                      |___/ 
I|15:35:31.390977|----|-|main|main.go:275 Version : v1.0.2-4-g1406727-dirty
I|15:35:31.390996|----|-|main|main.go:276 Build   : darwin/amd64 tags()-2023-06-14-15:35:27
D|15:35:32.003336|b6b5|-|main|main.go:330 LogWriterConfig filename is empty string, will be ignore
D|15:35:32.003381|b6b5|-|main|main.go:367 LogForwarderConfig vendor and address is empty string, will be ignore
D|15:35:32.003392|b6b5|-|main|linkfactory.go:49  
D|15:35:32.003450|f39F|-|main|main.go:330 LogWriterConfig filename is empty string, will be ignore
D|15:35:32.003459|f39F|-|main|main.go:367 LogForwarderConfig vendor and address is empty string, will be ignore
D|15:35:32.003467|f39F|-|main|linkfactory.go:63  .relay/0x3.icon
D|15:35:32.108162|f39F|-|ethbr|receiver.go:236 ReceiveLoop height:211 seq:3 filterQuery[Address:0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9,Topic:0x37be353f216cf7e33639101fd610c542e6a0c0109173fa1c1d8b04d34edb7c1b]
D|15:35:32.129774|f39F|-|ethbr|receiver.go:261 event[seq:2] seq:3 dst:btp://0x3.icon/cx665ece3eec7593670c4d6660594aead32319c1f9
D|15:35:32.130329|f39F|-|ethbr|receiver.go:261 event[seq:3] seq:3 dst:btp://0x3.icon/cx665ece3eec7593670c4d6660594aead32319c1f9
D|15:35:32.166538|b6b5|-|client|client.go:330 MonitorBTP WSEvent [::1]:54747 WSEventInit
D|15:35:32.166622|b6b5|-|btp2|btp2.go:312 ReceiveLoop monitorBTP2Block height:14034 seq:3 networkId:6 connected [::1]:54747
**D|15:35:59.506603|f39F|-|ethbr|receiver.go:261 event[seq:4] seq:3 dst:btp://0x3.icon/cx665ece3eec7593670c4d6660594aead32319c1f9
D|15:35:59.507543|f39F|-|ethbr|receiver.go:261 event[seq:5] seq:3 dst:btp://0x3.icon/cx665ece3eec7593670c4d6660594aead32319c1f9**
D|15:35:59.507580|f39F|-|ethbr|receiver.go:303 monitor info : Height:282  RpsCnt:2 LastSeq:5 
D|15:35:59.507679|f39F|-|ethbr|receiver.go:133 OnBlockOfSrc rpsCnt:2 rxSeq:5
D|15:35:59.509201|f39F|-|ethbr|receiver.go:187 BuildRelayMessage height:282 data:-QGb-QGYuMr4yAC4wvjA-L6giw5NR3uba8dCJuMX_beUJMq5Uwdpg2w04i0ajfQkI1sEuJr4mI0weDUzOS5oYXJkaGF0iDB4My5pY29uhXhjYWxsALhn-GUBuGL4YKoweDk1OTkyMmJFM0NBZWU0YjhDZDlhNDA3Y2MzYWMxQzI1MUMyMDA3QjGqY3g5YWE1MTg1MDY3ZTYyNTI3OGFiYzI1MWQ4NjRlOWVlODQ2Y2NhMTcxAwCHS3VwdGwtMATPjTB4NTM5LmhhcmRoYXTAggEauMr4yAG4wvjA-L6giw5NR3uba8dCJuMX_beUJMq5Uwdpg2w04i0ajfQkI1sFuJr4mI0weDUzOS5oYXJkaGF0iDB4My5pY29uhXhjYWxsALhn-GUBuGL4YKoweDk1OTkyMmJFM0NBZWU0YjhDZDlhNDA3Y2MzYWMxQzI1MUMyMDA3QjGqY3g5YWE1MTg1MDY3ZTYyNTI3OGFiYzI1MWQ4NjRlOWVlODQ2Y2NhMTcxBACHS3VwdGwtMQXPjTB4NTM5LmhhcmRoYXTAggEa 
D|15:35:59.509883|f39F|-|icon|sender.go:141 _relay src address:btp://0x539.hardhat/0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9, rm id:3276127245330160829, rm msg:f9019bf90198b8caf8c800b8c2f8c0f8bea08b0e4d477b9b6bc74226e317fdb79424cab9530769836c34e22d1a8df424235b04b89af8988d30783533392e68617264686174883078332e69636f6e857863616c6c00b867f86501b862f860aa307839353939323262453343416565346238436439613430376363336163314332353143323030374231aa6378396161353138353036376536323532373861626332353164383634653965653834366363613137310300874b7570746c2d3004cf8d30783533392e68617264686174c082011ab8caf8c801b8c2f8c0f8bea08b0e4d477b9b6bc74226e317fdb79424cab9530769836c34e22d1a8df424235b05b89af8988d30783533392e68617264686174883078332e69636f6e857863616c6c00b867f86501b862f860aa307839353939323262453343416565346238436439613430376363336163314332353143323030374231aa6378396161353138353036376536323532373861626332353164383634653965653834366363613137310400874b7570746c2d3105cf8d30783533392e68617264686174c082011a
D|15:36:03.546369|f39F|-|icon|sender.go:207 result success rm id : 3276127245330160829 , txHash : 0xcff1a62a4ba14c3dc62efe62c76cfbd9167b836cbdfa4ed1bfeb989b4e780f41
D|15:36:03.547673|f39F|-|ethbr|receiver.go:221 clear receive data (height:282, seq:5)

**Comment by shanithkk** [comment]
@kwon528 
can you check the same scenario by using this [dapps](https://github.com/HugoByte/btp-dapp-sample)
https://github.com/HugoByte/btp-dapp-sample 
please let me know if this error arise from my end, thank you

**Comment by kwon528** [comment]
@shanithkk 
As a result of testing through HugoByte/btp-dapp-sample, the same error occurred, so I corrected it. Not only relay but also java bridge bmv were modified in this modification, so you can deploy the newly build contract and test it.
Thank you for your confirmation.

**Comment by shanithkk** [comment]
@kwon528  Thank you it is working fine now.
